var Config = {};
Config.webkitUseRegistry = "" || "YES";
Config.PID = "iLividNewTab";
//Config.CRX_VER = chrome.app.getDetails().version;
Config.CRX_VER = "1.0";
Config.CRX_TYPE = "S"
Config.phoneHomeURL = "http://phn.apnanalytics.com/tr.gif?" +
                        "anxtv={anxtv}" +
                        "&anxv={anxv}" +
                        "&crxv=" + Config.CRX_VER +
                        "&anxt={guid}" +
                        "&tpid={PID}" +
                        "&anxp={p2}" +
                        "&o={o}" +
                        "&apn_dbr={dbr}" +
                        "&locale={locale}" +
                        "&anxa=APNToolbar" +
                        "&anxe=PhoneHome" +
                        "&anxr=" + new Date().getTime() +
                        "&pt={ProductType}" +
                        "&trgb={trgb}" +
                        "&doi={doi}" +
                        "&pf={pf}" +
                        "&browsers={Browsers}" +
                        "&tbs={tbsinstalled}" +
                        "&crxtype=" + Config.CRX_TYPE +
                        "&fparam=";
Config.clickReportingURL = "http://anx.apnanalytics.com/tr.gif?" +
                        "anxtv={anxtv}" +
                        "&anxv={anxv}" +
                        "&crxv=" + Config.CRX_VER +
                        "&anxt={guid}" +
                        "&tpid={PID}" +
                        "&anxp={p2}" +
                        "&o={o}" +
                        "&apn_dbr={dbr}" +
                        "&locale={locale}" +
                        "&anxa=APNButtons" +
                        "&anxe=ButtonClick" +
                        "&buttonName=BrowserAction" +
                        "&buttonPosition=0" +
                        "&anxr=" + new Date().getTime() +
                        "&pt={ProductType}" +
                        "&trgb={trgb}" +
                        "&doi={doi}" +
                        "&pf={pf}" +
                        "&browsers={Browsers}" +
                        "&tbs={tbsinstalled}";
Config.searchURL = "http://dts.search.ask.com/sr?" +
                        "gct=bar" +
                        "&o={o}" +
                        "&v={v}" +
                        "&d={d}" +
                        "&t={t}" +
                        "&appid={appid}" +
                        "&systemid={sysid}" +
                        "&apn_uid={apn_uid}" +
                        "&apn_ptnrs={apn_ptnrs}" +
                        "&apn_dtid={apn_dtid}" +
                        "&qsrc=2871" +
                        "&l=dis" +
                        "&sver=3" +
                        "&browsers={Browsers}" +
                        "&trgb={trgb}" +
                        "&locale={locale}" +
                        "&dateOfInstall={doi}" +
                        "&psv={psv}" +
                        "&q=";
Config.newTabSearchURL = "http://dts.search.ask.com/sr?" +
                        "gct=tab" +
                        "&o={o}" +
                        "&v={v}" +
                        "&d={d}" +
                        "&t={t}" +
                        "&appid={appid}" +
                        "&systemid={sysid}" +
                        "&apn_uid={apn_uid}" +
                        "&apn_ptnrs={apn_ptnrs}" +
                        "&apn_dtid={apn_dtid}" +
                        "&qsrc=2871" +
                        "&l=dis" +
                        "&sver=3" +
                        "&browsers={Browsers}" +
                        "&trgb={trgb}" +
                        "&locale={locale}" +
                        "&dateOfInstall={doi}" +
                        "&psv={psv}" +
                        "&q=";
